***CUDA (Compute Unified Device Architecture)*** is NVIDIA's parallel computing platform and programming model that lets you harness the power of GPUs for general-purpose computing tasks—not just graphics rendering.


### **🚀 What CUDA Enables**

- Massively parallel processing: GPUs have thousands of cores, and CUDA lets you run computations across them simultaneously.
- High-performance computing: Ideal for tasks like deep learning, scientific simulations, image processing, and large-scale data analysis.
- GPU acceleration: You can offload heavy computations from the CPU to the GPU, often achieving 10x–100x speedups


In [2]:
import torch
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

PyTorch version: 2.7.1+cpu
CUDA available: False


***Tensors are the fundamental building blocks of PyTorch. Think of them as multi-dimensional arrays that can run on GPUs***

## 🧠 What Is a Tensor?
A tensor is a multi-dimensional array:
- Scalar → 0D tensor (e.g., 5)
- Vector → 1D tensor (e.g., [1, 2, 3])
- Matrix → 2D tensor (e.g., [[1, 2], [3, 4]])
- Higher-order tensors → 3D and beyond (e.g., images, videos, batches of data)


### 📐 Shape: The Layout of the Tensor

The shape tells you how many elements exist along each dimension of a tensor. It’s expressed as a tuple.
- Example: A tensor with shape (2, 3) means:
- 2 rows
- 3 columns
- Total of 6 elements


### 🧭 Rank: Number of Dimension

The rank is the number of dimensions (or axes) the tensor has.
- Scalar → Rank 0
- Vector → Rank 1
- Matrix → Rank 2
- 3D tensor → Rank 3 (e.g., batch of images)

### 🔢 Size: Total Number of Elements
The size is the total count of elements in the tensor. It’s the product of all dimensions in the shape.
- For shape (2, 3), size = 2 × 3 = 6





In [10]:
import torch

# Scalar (0D tensor) - just a single number

scalar = torch.tensor(5)
print(f"Scalar: {scalar}")
print(f"Shape: {scalar.shape}")
print ("rank : ", scalar.ndim)


Scalar: 5
Shape: torch.Size([])
rank :  0


In [11]:
# Vector (1D tensor) - like a list of numbers

vector = torch.tensor([1, 2, 3, 4])
print(f"Vector: {vector}")
print(f"Shape: {vector.shape}")
print(f"rank: {vector.ndim}")

Vector: tensor([1, 2, 3, 4])
Shape: torch.Size([4])
rank: 1


In [12]:
# Matrix (2D tensor) - like a spreadsheet

matrix = torch.tensor([[1,2],[3,4],[5,5]])
print (matrix)
print (matrix.shape)
print(f"rank: {matrix.ndim}")


tensor([[1, 2],
        [3, 4],
        [5, 5]])
torch.Size([3, 2])
rank: 2


In [14]:
# Matrix (2D tensor) - like a spreadsheet

matrix1 = torch.tensor([[1,2,1,13],[3,4,1,11],[5,6,1,19]])
print (matrix)
print (matrix.shape)
print ("rank",matrix.ndim)


tensor([[ 1,  2,  1, 13],
        [ 3,  4,  1, 11],
        [ 5,  6,  1, 19]])
torch.Size([3, 4])
rank 2


In [16]:
 # 3D tensor - like a stack of matrices

tensor_3d = torch.tensor([[[1,2,3], [3,4,4], [4,5,1]]])
print (tensor_3d)
print (tensor_3d.shape)
print (tensor_3d.ndim)

tensor([[[1, 2, 3],
         [3, 4, 4],
         [4, 5, 1]]])
torch.Size([1, 3, 3])
3


### Creating Tensors

In [9]:
# Create tensors with specific values
import torch
zeros = torch.zeros([3, 4,1])
print (zeros)
print (zeros.ndim)
print (zeros.size())
print (zeros.numel())

tensor([[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]])
3
torch.Size([3, 4, 1])
12


In [11]:
ones = torch.ones(2, 3,1,2)
print (ones)
print (ones.shape)
print (ones.ndim)


tensor([[[[1., 1.]],

         [[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]],

         [[1., 1.]]]])
torch.Size([2, 3, 1, 2])
4


- Create tensor with specific data typ

In [14]:
float_tensor = torch.tensor([1,1,2.2], dtype= torch.float32)
print (float_tensor)

tensor([1.0000, 1.0000, 2.2000])


In [19]:
ones = torch.ones(2, 3, dtype= torch.int8) 
print (ones)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)


In [25]:
## 5x5 matrix of zeros
zeros_5 = torch.zeros(5,5)
print(zeros_5.shape)
print(zeros_5.ndim)
print(zeros_5.numel())
print(zeros_5.size())

torch.Size([5, 5])
2
25
torch.Size([5, 5])


In [26]:
array_1d = torch.tensor([10, 20, 30, 40, 50])
print(array_1d.shape)
print(array_1d.ndim)


torch.Size([5])
1


In [27]:
## A 2x3 matrix of random numbers

random_1 = torch.randn(2, 3)
print (random_1.shape)
print (random_1.ndim)


torch.Size([2, 3])
2


In [41]:
# A 3x3 identity matrix (hint: use torch.eye())

torch_eye = torch.eye(3, dtype=torch.float16)
print (torch_eye)
print (torch_eye.shape)
print (torch_eye.ndim)


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float16)
torch.Size([3, 3])
2


## 4. Basic Tensor Operations
- Mathematical Operations

In [46]:
 # Create sample tensors
 a = torch.tensor([1, 2, 3])
 b = torch.tensor([4, 5, 6])

 # Basic arithmetic
 print("Addition:", a + b)
 print("Subtraction:", a - b)
 print("Multiplication:", a * b)
 print("Division:",(a / b))

Addition: tensor([5, 7, 9])
Subtraction: tensor([-3, -3, -3])
Multiplication: tensor([ 4, 10, 18])
Division: tensor([0.2500, 0.4000, 0.5000])


In [54]:
# Matrix operations
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[5, 6], [7, 8]])

print("Matrix addition:\n", matrix_a + matrix_b)
print ("=============================================="*2)

print("Matrix multiplication:\n", torch.matmul(matrix_a, matrix_b))

print ("=============================================="*2)

# or use @ operator
print("Matrix multiplication (@ operator):\n", matrix_a @ matrix_b)

print ("=============================================="*2)

Matrix addition:
 tensor([[ 6,  8],
        [10, 12]])
Matrix multiplication:
 tensor([[19, 22],
        [43, 50]])
Matrix multiplication (@ operator):
 tensor([[19, 22],
        [43, 50]])


### Reshaping a tensor

In [55]:
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Original shape:", x.shape)
print("Original tensor:\n", x)

Original shape: torch.Size([2, 4])
Original tensor:
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [56]:
reshaped = x.view(4, 2)  # 4 rows, 2 columns
print("Reshaped (4, 2):\n", reshaped)

Reshaped (4, 2):
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [67]:
y = torch.tensor([[1,2,3],[2,2,2]])
print (y.shape)
print (y.ndim)
print (y)

torch.Size([2, 3])
2
tensor([[1, 2, 3],
        [2, 2, 2]])


In [66]:
new_y = y.view([3,2])
print(new_y)

tensor([[1, 2],
        [3, 2],
        [2, 2]])
